In [13]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

dataset = pd.read_csv("Data.csv")
x = dataset.iloc[:, :-2].values
y = dataset.iloc[:, [3, 4]]
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])


ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
le = LabelEncoder()
y = y.apply(LabelEncoder().fit_transform)
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=1)
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x[:, 3:] = sc.transform(x[:, 3:])
print("\n")
print(x_train)
print(x_test)



[[0.0 0.0 1.0 -0.1435168817394798 -1.1996846865850523]
 [0.0 1.0 0.0 0.05443743790118133 -0.12534019113575173]
 [1.0 0.0 0.0 1.004618172176356 0.3043976070439685]
 [0.0 0.0 1.0 -1.1332884799427871 1.5219880352198425]
 [0.0 0.0 1.0 -1.6083788470803746 -1.486176552038199]
 [1.0 0.0 0.0 1.123390763960753 0.7341354052236887]
 [0.0 1.0 0.0 1.24216335574515 0.9490043043135489]
 [1.0 0.0 0.0 -0.5394255210208029 -0.6983239220420454]]
[[0.0 1.0 0.0 30.0 55000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
